"""
Serves the Claude Skills for HR Ops library.

One process does three jobs:
  - serves the per-skill pages generated by site/build.py
  - hands out the real installable .zip for each skill
  - gates the full pack behind an email

On boot it builds anything missing, so a fresh clone runs with no setup.

    python3 main.py            # http://localhost:8080
    BUILD=always python3 main.py   # rebuild pages and packages first
"""

import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime, timezone

from flask import (Flask, Response, abort, redirect, request,
                   send_file, send_from_directory)

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, "site", "out")
DIST = os.path.join(ROOT, "dist")
DATA = os.path.join(ROOT, "data")
LEADS = os.path.join(DATA, "leads.jsonl")
PORT = int(os.environ.get("PORT", 8080))

SLUG = re.compile(r"^[a-z0-9][a-z0-9-]{1,80}$")
app = Flask(__name__)


# ----------------------------------------------------------------- build

def run(label, *cmd):
    print(f"[build] {label}...", flush=True)
    proc = subprocess.run([sys.executable, *cmd], cwd=ROOT,
                          capture_output=True, text=True)
    if proc.returncode:
        print(f"[build] {label} FAILED\n{proc.stdout}\n{proc.stderr}", flush=True)
    else:
        print(f"[build] {label} ok", flush=True)
    return proc.returncode == 0


def ensure_built():
    force = os.environ.get("BUILD") == "always"
    if force or not os.path.isdir(OUT) or not os.listdir(OUT):
        run("pages", "site/build.py")
    if force or not os.path.isdir(DIST) or not os.listdir(DIST):
        run("packages", "tools/package.py")


# ----------------------------------------------------------------- catalogue

def catalogue():
    """Every skill on disk, with whether it has a rich page and a package."""
    import glob
    items = []
    paths = (sorted(glob.glob(os.path.join(ROOT, "skills", "*", "*.md")))
             + sorted(glob.glob(os.path.join(ROOT, "skills", "*", "*", "SKILL.md"))))
    for path in paths:
        rel = os.path.relpath(path, ROOT).split(os.sep)
        category = rel[1]
        slug = (os.path.basename(os.path.dirname(path))
                if os.path.basename(path) == "SKILL.md" else rel[-1][:-3])
        text = open(path, encoding="utf-8").read()
        match = re.search(r"^description:\s*(.+)$", text, re.M)
        items.append({
            "slug": slug,
            "category": category,
            "description": match.group(1).strip() if match else "",
            "page": os.path.exists(os.path.join(OUT, slug + ".html")),
            "zip": os.path.exists(os.path.join(DIST, slug + ".zip")),
            "engine": os.path.exists(os.path.join(
                ROOT, "skills", category, slug, "scripts", "analyze.py")),
        })
    return sorted(items, key=lambda i: (i["category"], i["slug"]))


# ----------------------------------------------------------------- index page

INDEX_CSS = """
:root{--ground:#fff;--raised:#f8fafc;--line:#e2e8f0;--ink:#0f172a;--soft:#404d5f;
--muted:#687281;--accent:#4f46e5;--deep:#3730a3;
--sans:'Plus Jakarta Sans',-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;
--mono:ui-monospace,'SF Mono',Menlo,Consolas,monospace}
@media (prefers-color-scheme:dark){:root{--ground:#0b1120;--raised:#121b2d;--line:#22304a;
--ink:#e7edf7;--soft:#b3bfd2;--muted:#8494ad;--accent:#9a95ff;--deep:#c3bfff}}
*{box-sizing:border-box}
body{margin:0;background:var(--ground);color:var(--ink);font-family:var(--sans);
font-size:16px;line-height:1.55;-webkit-font-smoothing:antialiased}
.wrap{max-width:900px;margin:0 auto;padding-inline:20px;padding-block:56px 72px}
a{color:var(--accent);text-decoration:none}a:hover{color:var(--deep);text-decoration:underline}
h1{font-size:clamp(32px,5vw,44px);line-height:1.08;letter-spacing:-.03em;margin:8px 0 0;font-weight:800}
.eyebrow{font-family:var(--mono);font-size:12px;letter-spacing:.14em;text-transform:uppercase;
color:var(--muted);margin:0;font-weight:500}
.lead{font-size:19px;color:var(--soft);margin:16px 0 0;max-width:62ch}
.cta{display:flex;gap:12px;flex-wrap:wrap;margin-top:28px}
.btn{display:inline-block;padding:12px 20px;border-radius:10px;font-weight:600;font-size:15px}
.btn--p{background:var(--accent);color:#fff}.btn--p:hover{background:var(--deep);color:#fff;text-decoration:none}
.btn--s{border:1px solid var(--line);color:var(--ink)}.btn--s:hover{border-color:var(--accent);text-decoration:none}
h2{font-size:14px;letter-spacing:.1em;text-transform:uppercase;color:var(--muted);
margin:44px 0 12px;font-weight:600;font-family:var(--mono)}
.row{display:grid;grid-template-columns:230px 1fr auto;gap:8px 20px;padding:14px 0;
border-top:1px solid var(--line);align-items:baseline}
.row b{font-weight:600;font-size:15.5px}
.row p{margin:0;color:var(--soft);font-size:14.5px}
.row .get{font-family:var(--mono);font-size:12.5px;white-space:nowrap}
.tag{font-family:var(--mono);font-size:10.5px;letter-spacing:.06em;text-transform:uppercase;
border:1px solid var(--line);border-radius:999px;padding:2px 7px;color:var(--muted);margin-left:8px}
footer{margin-top:56px;border-top:1px solid var(--line);padding-top:20px;color:var(--muted);font-size:13.5px}
@media(max-width:700px){.row{grid-template-columns:1fr}}
"""

TITLES = {
    "writing": "Writing", "sourcing": "Sourcing", "screening": "Screening",
    "interviewing": "Interviewing", "analysing": "Analysing", "onboarding": "Onboarding",
    "complying": "Complying", "retaining": "Retaining", "operating": "Operating",
}


def esc(value):
    return (value.replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


@app.get("/claude-skills")
def index():
    items = catalogue()
    groups = {}
    for item in items:
        groups.setdefault(item["category"], []).append(item)

    rows = []
    for category in list(TITLES) + [c for c in groups if c not in TITLES]:
        if category not in groups:
            continue
        rows.append(f"<h2>{esc(TITLES.get(category, category.title()))}</h2>")
        for item in groups[category]:
            name = esc(item["slug"])
            label = (f'<a href="/claude-skills/{name}">{name}</a>'
                     if item["page"] else f"<b>{name}</b>")
            tag = '<span class="tag">tested engine</span>' if item["engine"] else ""
            get = (f'<a class="get" href="/download/{name}.zip">Download &darr;</a>'
                   if item["zip"] else '<span class="get">&mdash;</span>')
            rows.append(
                f'<div class="row"><div>{label}{tag}</div>'
                f'<p>{esc(item["description"])}</p><div>{get}</div></div>')

    engine_count = sum(1 for i in items if i["engine"])
    body = "\n".join(rows)
    return Response(f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Claude Skills for HR Ops</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap">
<style>{INDEX_CSS}</style></head><body><div class="wrap">
<p class="eyebrow">Free &middot; MIT &middot; {len(items)} skills</p>
<h1>Claude Skills for HR Ops</h1>
<p class="lead">Skills that make Claude useful to a frontline hiring team &mdash; high-volume
hourly hiring, multi-site operations, shift work. Download one, add it to Claude, describe
your problem. {engine_count} of them ship a tested analysis engine rather than asking the
model to do statistics in prose.</p>
<div class="cta">
  <a class="btn btn--p" href="/pack">Get the whole pack</a>
  <a class="btn btn--s" href="/data/frontline_pipeline_sample.csv">Sample dataset (CSV, 2.4&nbsp;MB)</a>
</div>
{body}
<footer>Published by Fountain. Every skill is MIT licensed &mdash; use it, change it,
ship it inside your own tooling.</footer>
</div></body></html>""", mimetype="text/html")


# ----------------------------------------------------------------- routes

@app.get("/")
def home():
    return redirect("/claude-skills", code=302)


@app.get("/claude-skills/<slug>")
def skill_page(slug):
    if not SLUG.match(slug):
        abort(404)
    path = os.path.join(OUT, slug + ".html")
    if not os.path.exists(path):
        abort(404)
    return send_file(path)


@app.get("/download/<slug>.zip")
def download(slug):
    if not SLUG.match(slug):
        abort(404)
    path = os.path.join(DIST, slug + ".zip")
    if not os.path.exists(path):
        abort(404)
    return send_file(path, as_attachment=True, download_name=f"{slug}.zip",
                     mimetype="application/zip")


@app.get("/data/<name>")
def sample(name):
    if not re.match(r"^[a-z0-9_.-]+\.csv$", name):
        abort(404)
    if not os.path.exists(os.path.join(DATA, name)):
        abort(404)
    return send_from_directory(DATA, name, as_attachment=True, mimetype="text/csv")


@app.get("/sitemap.xml")
def sitemap():
    path = os.path.join(OUT, "sitemap.xml")
    if not os.path.exists(path):
        abort(404)
    return send_file(path, mimetype="application/xml")


FAVICON = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">'
    '<rect width="32" height="32" rx="7" fill="#4f46e5"/>'
    '<path d="M8 9h16l-6 7v7l-4 2v-9z" fill="#fff"/></svg>'
)


@app.get("/favicon.ico")
@app.get("/favicon.svg")
def favicon():
    return Response(FAVICON, mimetype="image/svg+xml",
                    headers={"Cache-Control": "public, max-age=86400"})


@app.get("/healthz")
def healthz():
    items = catalogue()
    return {
        "ok": True,
        "skills": len(items),
        "pages": sum(1 for i in items if i["page"]),
        "packages": sum(1 for i in items if i["zip"]),
    }


# ----------------------------------------------------------------- email gate

EMAIL = re.compile(r"^[^@\s]+@[^@\s.]+\.[^@\s]{2,}$")
PACK = os.path.join(DIST, "frontline-hiring-pack.zip")


def pack_page(message="", tone="", email=""):
    note = (f'<p style="color:{"#b91c1c" if tone == "bad" else "#15803d"};'
            f'margin:14px 0 0;font-size:14.5px">{esc(message)}</p>' if message else "")
    return Response(f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Get the pack</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap">
<style>{INDEX_CSS}
form{{display:flex;gap:10px;flex-wrap:wrap;margin-top:26px}}
input{{font:inherit;padding:12px 14px;border:1px solid var(--line);border-radius:10px;
background:var(--ground);color:var(--ink);min-width:260px;flex:1}}
input:focus{{outline:2px solid var(--accent);outline-offset:1px}}
button{{font:inherit;font-weight:600;background:var(--accent);color:#fff;border:0;
padding:12px 22px;border-radius:10px;cursor:pointer}}
button:hover{{background:var(--deep)}}
</style></head><body><div class="wrap">
<p class="eyebrow">The whole library</p>
<h1>Get the pack</h1>
<p class="lead">All 43 skills as one download, each a separate installable file. Individual
skills stay free and ungated &mdash; <a href="/claude-skills">browse them here</a>. The pack
is one email, because we would like to know who is using this.</p>
<form method="post" action="/pack">
  <input id="email" name="email" type="email" required placeholder="you@company.com"
         autocomplete="email" value="{esc(email)}" aria-label="Work email">
  <button type="submit">Send me the pack</button>
</form>
{note}
<footer>We use it to tell you when skills change. Nothing else, and nothing shared.</footer>
</div></body></html>""", mimetype="text/html")


@app.get("/pack")
def pack_form():
    return pack_page()


@app.post("/pack")
def pack_submit():
    email = (request.form.get("email") or "").strip().lower()
    if not EMAIL.match(email) or len(email) > 254:
        return pack_page("That does not look like an email address.", "bad", email), 400
    if not os.path.exists(PACK):
        return pack_page("The pack is being rebuilt — try again in a moment.", "bad", email), 503

    os.makedirs(DATA, exist_ok=True)
    with open(LEADS, "a", encoding="utf-8") as fh:
        fh.write(json.dumps({
            "email": email,
            "at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "referer": (request.headers.get("Referer") or "")[:300],
        }) + "\n")
    print(f"[lead] {email}", flush=True)

    return send_file(PACK, as_attachment=True,
                     download_name="frontline-hiring-pack.zip",
                     mimetype="application/zip")


# ----------------------------------------------------------------- run

if __name__ == "__main__":
    started = time.time()
    ensure_built()
    print(f"[boot] ready in {time.time() - started:.1f}s — http://0.0.0.0:{PORT}", flush=True)
    app.run(host="0.0.0.0", port=PORT, debug=bool(os.environ.get("DEBUG")))
