#!/usr/bin/env python3
"""
Writes roadmap.json: the skills that exist but are not published yet.

Why they are not simply in skills/
----------------------------------
This repository is meant to be public. A skill that has not been through its
gate is not a product, and 41 of them sitting in skills/ would read as 41
products -- which is a claim we cannot support and, for three of them, one we
have not decided to make at all.

So the unreleased ones live in a private repository and only their *names*
travel: slug, title, category, one-line description, whether they will need a
data export. Enough for a reader to see where the library is going and leave
an address to hear about it, and not one line of content.

    python3 tools/roadmap.py --from ../skills-os-internal/skills   # regenerate
    python3 tools/roadmap.py                                        # show it

HELD below is not a technical exclusion. Those three contradict guidance
Fountain's own product gives, which is a decision about what this library says,
not about whether the files compile. Announcing them commits us to shipping
them, so they stay out of the roadmap until that decision is made. Removing a
name from HELD is all it takes to announce it.
"""

import argparse
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "roadmap.json")

HELD = {
    "screening-question-builder",
    "interview-slot-planner",
    "sourcing-gap-plan",
}

DATA_BLOCK_MARKER = ("**If your file contains a column that looks nominative, I will "
                     "stop and ask you to re-export rather than analyse it.**")


def published():
    """Whatever this repo already ships. A skill cannot be both available and
    coming soon, and the guard matters because the private repo will keep its
    own copy of anything that graduates until someone deletes it there."""
    path = os.path.join(ROOT, "dist", "catalogue.json")
    if not os.path.exists(path):
        return set()
    with open(path, encoding="utf-8") as fh:
        return {s["slug"] for s in json.load(fh)["skills"] if s["available"]}


def scan(skills_dir):
    live = published()
    entries = []
    paths = (sorted(glob.glob(os.path.join(skills_dir, "*", "*.md")))
             + sorted(glob.glob(os.path.join(skills_dir, "*", "*", "SKILL.md"))))
    for path in paths:
        parts = os.path.relpath(path, skills_dir).split(os.sep)
        category = parts[0]
        folder = os.path.dirname(path)
        slug = (os.path.basename(folder) if os.path.basename(path) == "SKILL.md"
                else parts[-1][:-3])
        if slug in HELD or slug in live:
            continue
        text = open(path, encoding="utf-8").read()
        description = re.search(r"^description:\s*(.+)$", text, re.M)
        heading = re.search(r"^# (.+)$", text, re.M)
        entries.append({
            "slug": slug,
            "title": heading.group(1).strip() if heading else slug,
            "category": category,
            "description": description.group(1).strip() if description else "",
            "needs_dataset": DATA_BLOCK_MARKER in text,
        })
    return sorted(entries, key=lambda e: (e["category"], e["slug"]))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--from", dest="src",
                    help="the private repo's skills/ directory to read")
    args = ap.parse_args()

    if args.src:
        entries = scan(args.src)
        doc = {
            "$comment": "Names only, of skills that exist but are not published. "
                        "Generated by tools/roadmap.py from the private repository; "
                        "no skill content travels. Regenerate when that repo changes.",
            "schema_version": 1,
            "coming_soon": entries,
        }
        with open(OUT, "w", encoding="utf-8") as fh:
            json.dump(doc, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        held = ", ".join(sorted(HELD))
        print(f"roadmap.json  {len(entries)} coming soon  (held back: {held})")
        return 0

    if not os.path.exists(OUT):
        raise SystemExit("No roadmap.json yet. Run with --from <private repo>/skills")
    with open(OUT, encoding="utf-8") as fh:
        doc = json.load(fh)
    print(f"{len(doc['coming_soon'])} coming soon")
    for e in doc["coming_soon"]:
        print(f"  {e['category']:<13} {e['slug']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
